version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: uvicorn api:app --host 0.0.0.0 --port 8000 --reload

  streamlit:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    depends_on:
      - api
    command: streamlit run app.py --server.port=8501 --server.enableCORS=false --server.enableXsrfProtection=false
